version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  api:
    build: .
    container_name: python_api
    environment:
      DB_HOST: database
      DB_NAME: crud_db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "sleep 10 && python app.py"

volumes:
  postgres_data:
